// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionOrders.API.Models.Data;

#nullable disable

namespace SolutionOrders.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionOrders.API.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Drukarki 3D FDM i inne urządzenia do druku przestrzennego",
                            IsActive = true,
                            Name = "Drukarki 3D"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Materiały eksploatacyjne do drukarek 3D, np. PLA, PET-G, TPU",
                            IsActive = true,
                            Name = "Filamenty"
                        },
                        new
                        {
                            IdCategory = 3,
                            Description = "Dysze do głowic drukarek 3D w różnych rozmiarach",
                            IsActive = true,
                            Name = "Dysze"
                        },
                        new
                        {
                            IdCategory = 4,
                            Description = "Powierzchnie robocze, nakładki PEI i akcesoria do stołów",
                            IsActive = true,
                            Name = "Stoły robocze"
                        },
                        new
                        {
                            IdCategory = 5,
                            Description = "Części zamienne i podzespoły do drukarek 3D",
                            IsActive = true,
                            Name = "Części"
                        },
                        new
                        {
                            IdCategory = 6,
                            Description = "Narzędzia serwisowe i akcesoria pomocnicze",
                            IsActive = true,
                            Name = "Narzędzia"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Adress = "ul. Główna 1, Warszawa",
                            IsActive = true,
                            Name = "Jan Kowalski",
                            PhoneNumber = "500-100-200"
                        },
                        new
                        {
                            IdClient = 2,
                            Adress = "ul. Kwiatowa 5, Kraków",
                            IsActive = true,
                            Name = "Anna Nowak",
                            PhoneNumber = "600-200-300"
                        },
                        new
                        {
                            IdClient = 3,
                            Adress = "ul. Leśna 12, Gdańsk",
                            IsActive = true,
                            Name = "Marek Wiśniewski",
                            PhoneNumber = "700-300-400"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnitOfMeasurement")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUnitOfMeasurement");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Code = "PRN001",
                            Description = "Popularna drukarka 3D FDM, idealna dla początkujących.",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Creality Ender 3 V3 SE",
                            Price = 1099m,
                            Quantity = 12m
                        },
                        new
                        {
                            IdItem = 2,
                            Code = "PRN002",
                            Description = "Kompaktowa i szybka drukarka 3D do zastosowań domowych.",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Bambu Lab A1 Mini",
                            Price = 1499m,
                            Quantity = 8m
                        },
                        new
                        {
                            IdItem = 3,
                            Code = "PRN003",
                            Description = "Nowoczesna drukarka 3D z automatycznym poziomowaniem stołu.",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Anycubic Kobra 2 Neo",
                            Price = 1299m,
                            Quantity = 6m
                        },
                        new
                        {
                            IdItem = 4,
                            Code = "FIL001",
                            Description = "Uniwersalny filament PLA do codziennych wydruków.",
                            IdCategory = 2,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Filament PLA Black 1kg",
                            Price = 79m,
                            Quantity = 40m
                        },
                        new
                        {
                            IdItem = 5,
                            Code = "FIL002",
                            Description = "Wytrzymały filament PET-G do bardziej wymagających projektów.",
                            IdCategory = 2,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Filament PET-G White 1kg",
                            Price = 89m,
                            Quantity = 25m
                        },
                        new
                        {
                            IdItem = 6,
                            Code = "FIL003",
                            Description = "Elastyczny filament TPU do specjalistycznych wydruków.",
                            IdCategory = 2,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Filament TPU Flexible 1kg",
                            Price = 119m,
                            Quantity = 15m
                        },
                        new
                        {
                            IdItem = 7,
                            Code = "NOZ001",
                            Description = "Standardowa mosiężna dysza 0.4 mm do drukarki 3D.",
                            IdCategory = 3,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Dysza 0.4 mm Brass",
                            Price = 15m,
                            Quantity = 100m
                        },
                        new
                        {
                            IdItem = 8,
                            Code = "NOZ002",
                            Description = "Komplet dysz o różnych średnicach do precyzyjnych wydruków.",
                            IdCategory = 3,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Zestaw dysz 0.2 / 0.4 / 0.6 / 0.8 mm",
                            Price = 39m,
                            Quantity = 40m
                        },
                        new
                        {
                            IdItem = 9,
                            Code = "BED001",
                            Description = "Elastyczna powierzchnia robocza PEI do drukarek 3D.",
                            IdCategory = 4,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Płyta PEI 235x235 mm",
                            Price = 89m,
                            Quantity = 20m
                        },
                        new
                        {
                            IdItem = 10,
                            Code = "BED002",
                            Description = "Gładka powierzchnia robocza do stołu drukarki 3D.",
                            IdCategory = 4,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Szkło hartowane 235x235 mm",
                            Price = 49m,
                            Quantity = 18m
                        },
                        new
                        {
                            IdItem = 11,
                            Code = "PRT001",
                            Description = "Wzmocniony ekstruder do popularnych drukarek 3D.",
                            IdCategory = 5,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Ekstruder metalowy MK8",
                            Price = 59m,
                            Quantity = 30m
                        },
                        new
                        {
                            IdItem = 12,
                            Code = "PRT002",
                            Description = "Pasek napędowy GT2 do osi drukarki 3D.",
                            IdCategory = 5,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Pasek GT2 5m",
                            Price = 25m,
                            Quantity = 22m
                        },
                        new
                        {
                            IdItem = 13,
                            Code = "TLS001",
                            Description = "Narzędzia do serwisu i wykańczania wydruków 3D.",
                            IdCategory = 6,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Zestaw kluczy i szczypiec do druku 3D",
                            Price = 45m,
                            Quantity = 35m
                        },
                        new
                        {
                            IdItem = 14,
                            Code = "TLS002",
                            Description = "Akcesorium pomocne przy zdejmowaniu modeli ze stołu.",
                            IdCategory = 6,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Szpachelka do zdejmowania wydruków",
                            Price = 19m,
                            Quantity = 50m
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime?>("DataOrder")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdWorker")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdWorker");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.OrderItem", b =>
                {
                    b.Property<int>("IdOrderItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderItem"));

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdOrderItem");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("IdUnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnitOfMeasurement"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUnitOfMeasurement");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            IdUnitOfMeasurement = 1,
                            Description = "Sztuki",
                            IsActive = true,
                            Name = "szt"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 2,
                            Description = "Kilogramy",
                            IsActive = true,
                            Name = "kg"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 3,
                            Description = "Metry",
                            IsActive = true,
                            Name = "m"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Worker", b =>
                {
                    b.Property<int>("IdWorker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWorker"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWorker");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            IdWorker = 1,
                            FirstName = "Piotr",
                            IsActive = true,
                            LastName = "Kowalczyk",
                            Login = "pkowalczyk",
                            Password = "haslo123"
                        },
                        new
                        {
                            IdWorker = 2,
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Wiśniewska",
                            Login = "mwisniewska",
                            Password = "haslo456"
                        },
                        new
                        {
                            IdWorker = 3,
                            FirstName = "Tomasz",
                            IsActive = true,
                            LastName = "Zieliński",
                            Login = "tzielinski",
                            Password = "haslo789"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Items")
                        .HasForeignKey("IdUnitOfMeasurement")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolutionOrders.API.Models.Worker", "Worker")
                        .WithMany("Orders")
                        .HasForeignKey("IdWorker")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.OrderItem", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Worker", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
